import struct
import xml.etree.ElementTree as ET
import json
from typing import TypedDict, Literal

Material = Literal[
	"Air",
	"Water",
	"Grass",
	"Slate",
	"Concrete",
	"Brick",
	"Sand",
	"WoodPlanks",
	"Rock",
	"Glacier",
	"Snow",
	"Sandstone",
	"Mud",
	"Basalt",
	"Ground",
	"CrackedLava",
	"Asphalt",
	"Cobblestone",
	"Ice",
	"LeafyGrass",
	"Salt",
	"Limestone",
	"Pavement",	
]
TEST_STR = """![CDATA[AQX///////////////+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4DMQqFCrYAdQuVC80KigA5CgoAM
Qs5C60KpgA1CgULggAxC00LxQq6ADUKDQuKADELPQvxCx4AOQt6ADEK+QvpC1IAOQsuADEKk
QutC1IAOQqyADEKlQu5C14AOQqmADEKbQvJC60KIgA1CmoAMQoZC6kLyQpyA/4D/gLtCukLH
gBxC8oICgA5CgYALggNCsIAMQtoCgAuCA0LFgAyCAYALggNCzoALQoCCAYALggNC9IAMggGA
C0LlggOADIIBgAtCyIIDgAxC3QKAC0K7ggOADELFAoALQqOCA0KCgAtCoQKAC0KAggNCpIAM
AoD/gP+Aq0KtggFC1YAaQomCA0LJgA1C3YAKQsyCBIAMggGACkKzggSAC0LZggGACkKeggSA
C0LcggGAC4IEgAtCroIBgAuCBEKOgAuCAYALggRCq4ALggGAC4IEQryAC4IBgAuCBELegAuC
AYALQtyCBIALQs0CAAAAAAAAAAAAAAABgP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4ANQtdC7EKhgBxC2ELs
QqKAHELYQvpCuoAcQs5C+0LHgBxCt0LwQsmAHEK2Qu9CyIAcQrNC+ELdgBxCpUL1QueAHEKV
QudC3IAcQpdC6kLfgBxCnELzQuxCiIAbQpRC7ULpQomAG0KDQttC2IAcQo9C7ELrQo6AG0Ki
QvRC50KAgBtCoULnQs6AHEKsQvJC2YAcQsBC/ELWgBxCuULkQrCAHELMQvhCw4AcQsRC+ULR
gBxCt0L7QuCAHEKUQt1CyYDhSISAHUjYSOhIoYAbSIBI50j0SNeAF4IDQrWADAKADIIDQruA
DAKADIIDQtuADELogAyCA0L1gAxCvYAMQuGCA4AMQpSADELdggOAGkLOggNChgBCjEKKAEKR
QoKAAkKGQoKADkKzggNC6ULYQu5C6kLcQvBC6ELRQuBC6ELsQulC5ULXgAxCn4IDQvBC30L0
Qu5C4ELzQvRC5UL1QvhC90L1QvJC5IAMQqKCA0KZQopCm0KUQohCl0KhQptCqkKowqIBQqBC
k4AMQqSCA0KCgBlCmIIDQoaAGUKIggOAGkKRggNCj4AZQq+CA4AaQrmCA4AaQsSCA4AaQuaC
A4AaQu+CAkLpgBqCA0LvgBpC8YIDgBpC1IIDgBpCqIIDgBtC3IIBQqGAvkjEiAFI+IAbiANI
woARSJqAB4gESImAFEK+ggSAC0KoAoALQrKCBIALQocCgAtCnIIEgAwCgAyCBIAMAoAMggRC
gYALQvOADIIEQo8AQodChgBCj4AGQteADIISgAyCEoAMghKADIISgAyCBELeQpFCoEKYQotC
mUKrQq5CvkK3QqxCrUKsQp+ADEL3ggNC44AZQuSCA0LYgBlC74IDQuyAGYIEQtCAGYIEQrCA
GYIEQqqAGYIEQpGAGYIEgBqCBIAaggRCjoAZggRCuoAZggRCpIAZQpSCA4AcQrNCoICASMRI
2UiTgBuIA0iwgBlIxogEgBBIu0j5SNaABUjRiARI5oAIAAAAAAAAAAAAAAABgP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4AHSJaACEjnSPVI9Ei3gBBIv0jwSM6ABkiKSN1I1UjxSOlIhYAPSM1I90j6SLeA
BUiZSO9I5kjXSPRIyYAPSLZI5Uj6SNyABUitSPdI4ki1SOpI6EidgA5Iwkj6SOtI9EiegARI
vEj7SNkASNtI7kjNgA5Iz0j8SMdI9kjdgARIz0j4SL8ASKRI80jiSLSADUjZSPtIu0jfSO9I
toADSNdI6EisgAFIuEj6SNtIloAMSN1I6kiZSMlI8EjXSIKAAkjbSO1In4ABSIVIxkj8SM+A
DEjbSOhIl0iHSOpI8EitgAFIm0jzSOxIioACSKRI10j6SLuACkicSPNI7EiIAEi3SPtI3IAB
SLBI8kjUgARIuUjjSPNIuYAJSJZI6kjggAFIi0jYSPhItwBIxUj6SMyABUjMSPZI6Ui4gAhI
k0jmSNyAAkjASONI4EiCSNZI/Ei/gAZIxUj5SOZIrYAHSKJI9UjpSIKAAUiNSOdI5Ei1SNlI
8kirgAdI4Uj8SOlIn4AGSJhI6EjZgANIv0j6SOFI7EjwSKCAB0ieSOFI70ilgAZInEjsSN2A
A0iDSOBI8Uj3SOWACUiESJeACEiSSIWABEioSO5I+kjXgBxItUjbSLuA/4DzSIyIAkixgAWI
BEj8gA5I+IgDSJmAA0iTiAVIqoANiARI6IADSKKIBoANSOaIBIADSMKIBkivgAxI64gESNyA
AkjeiAeADIgGSIGAAYgDSOyIA0j3gAuIBkjdgAGIA0jTiARIyIADSIKABYgHSIgAiANIsEih
iARInYACSKuABYgHSPBIoogDSIUASM+IBEiBgAEIgARIpIgDSP6IA0jNiAOAAkj5iASAAQiA
BEifiANIp4gDSPOIA4ACSH+IBEjxAEi6gARInIgDAIgHSOeAA0iniARI+UiTgARIrogDAEiR
iAZIw4AESKSIBEizgARIp4gDgAFI74gFSLiABUjdiANIuYAESKqIA4ABSKaIBYAHSOiIAoAG
iAJI04ACSOGIBIAISItInoAISJZIiYAEiANI+4AbSPOIAUiCgP+A0kjqiAOABEjOiAVIloAN
iARI+IADSPGIBoAMSIOIBYADiAdIqoAMiAVI1IACiAiADIgGgAKICEjOgAuIBkjdAEiGiAlI
kIADSIaABEiciAcASLiICoADSN6ABEjGiAdI5UjTiApI/YACCIAESNqIDUjhAIgFSN0ASIII
gASIDkiwAEitiAVI2QAIgASIDkiVgAFI24gFSMAIgARI/IgDSMuICIADiAZI8oAEiARI00jv
iAeABIgGgASIBEi/SJWIB4AFiAWABIgESMIAiAZI2oAFSKWIA0jAgARIrogDgAKIBUiZgAdI
6Ej+SLKABkikSPVI5oADSMSIBIAaSNGIAkjegBxIpUiGgP+ArQAA/wAA/wAA/wAB/oD/gP+A
q0KuggFC1oAaQoqCA0LKgA1C3oAKQsyCBIAMggGACkK0ggSAC0LaggGACkKfggSAC0LdggGA
CkKAggSAC0KvggGAC4IEQo+AC4IBgAuCBEKrgAuCAYALggRCvYALggGAC4IEQt+AC4IBgAtC
3YIEgAtCzgKA/4D/gKxCvELJgBxC9YICgA5Cg4ALggNCsoAMQt0CgAuCA0LIgAtCgIIBgAuC
A0LRgAtCgoIBgAuCA0L2gAyCAYALQueCA4AMggGAC0LLggOADELgAoALQr6CA4AMQsgCgAtC
poIDQoSAC0KkAoALQoOCA0KmgAwCgP+A/4DMQqVCsoAcQoFC6kL4QqaADkKGgAxC0kLwQq2A
DUKFQuWADELYQvVCsoANQodC54AMQtMCQsuADkLjgAxCwwJC2IAOQtCADEKoQu9C2YAOQrGA
DEKpQvNC3IAOQq6ADEKgQvdC70KMgA1CnoAMQopC70L3QqCADUKCgP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/wAAAAAAAAAAAAAAAYALQr6CBIALQqkCgAtCs4IEgAtCiAKAC0KdggSADAKADIIEgAwCgAyC
BEKCgAtC9IAMggRC20LKQuNC4kLUQuxC0UK7QrhCyULXQtJCy0LYgAyCEoAMghKADIISgAyC
EoAMggVC7gJC9kLnQveCBkL+gAxC+IIDQuSAGULlggNC2YAZQu+CA0LtgBmCBELRgBmCBEKx
gBmCBEKrgBmCBEKSgBmCBIAaggSAGoIEQo+AGYIEQruAGYIEQqWAGUKVggOAHEKzQqCAgEjF
SNpIlIAbiANIsYAZSMeIBIAQSLxI+kjXgAVI0ogESOeAFYIDQreADAKADIIDQr6ADAKADIID
Qt2ADELrgAyCA0L4gAxCwIAMQuSCA4AMQpeADELgggNC20LKQuNC4kLUQuxC0UK7QrhCyULX
QtJCy0K+gAxC0IIRgAxCtYIRgAxCooIRgAxCpYIRgAxCpoIEQu4CQvZC50L3ggZC/oAMQpqC
A0KJgBlCioIDQn+AGUKTggNCkYAZQrGCA4AaQryCA4AaQseCA4AaQuiCA4AaQvGCAkLsgBqC
A0LygBpC84IDgBpC1oIDgBpCqoIDgBtC3oIBQqSAoEiAgBxIx4gBSPuAG4gDSMSAEUidgAeI
BEiMgBZC20LwQqWAHELcQvFCpoAcQt0CQr6AHELSAkLLgBxCu0L1Qs2AHEK6QvRCzABCgABC
h0KGAEKPgBVCt0L9QuFC84INgA1CqUL6QuuCDoANQplC7ELggg6ADUKbQu9C44IOgA1CoEL4
QvBCjEKgQpFCoEKYQotCmUKrQq5CvkK3QqxCrUKsQp+ADUKYQvJC7kKNgBtCh0LfQtxCgYAb
QpPC8AFCkoAbQqZC+ULsQoSAG0KlQutC0oAcQrBC90LdgBxCxAJC2oAcQr1C6EK0gBxC0EL9
QseAHELIQv5C1YAcQrsCQuWAHEKZQuJCzoDhSIiAHUjcSO1IpYAbSIRI7Ej5SNuA3EKGAEKM
QooAQpFCgoACQoZCgoASQptC6ULYQu5C6kLcQvBC6ELRQuBC6ELsQulC5ELXgBBCokLwQt9C
9ELuQuBC80L0QuVC9UL4QvdC9ULyQuSAEUKZQopCm0KUQohCl0KhQptCqkKowqIBQqBCk4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4C/AAAAAAAAAAAAAAABgAVI64gDgARIz4gFSJeADYgESPmAA0jyiAaADEiE
iAWAA4gHSKuADIgFSNWAAogIgAyIBoACiAhIz4ALiAZI3gBIh4gJSJGAA0iHgARInYgHAEi5
iAqAA0jfgARIx4gHSOZI1IgKSP6AAgiABEjbiA1I4gCIBUjeAEiDCIAEiA5IsQBIrogFSNoA
CIAEiA5IloABSNyIBUjBCIAESP2IA0jMiAiAA4gGSPOABIgESNRI8IgHgASIBoAEiARIwEiW
iAeABYgFgASIBEjDAIgGSNuABUimiANIwYAESK+IA4ACiAVImoAHSOkISLOABkilSPZI54AD
SMWIBEiAgBlI0ogCSN+AHEimSIeA/4CzSI+IAkizgAWIBYAOSPuIA0icgANIlYgFSK2ADYgE
SOuAA0iliAaADUjpiASAA0jEiAZIsYAMSO6IBEjfgAJI4IgHgAyIBkiEgAGIA0jviANI+oAL
iAZI4IABiANI1ogESMuAA0iFgAWIB0iLAIgDSLNIo4gESKCAAkiugARIgYgHSPNIpIgDSIcA
SNKIBEiEgAEIgARIpogISNCIA4ACSPyIBEiAAAiABEiiiANIqYgDSPaIA4ACSIKIBEjzAEi+
gARIn4gDAIgHSOqAA0ipiARI/EiXgARIsYgDAEiTiAZIxoAESKeIBEi2gARIqYgDgAFI8YgF
SLuABUjfiANIvIAESK2IA4ABSKiIBUiBgAZI64gCgAaIAkjWgAJI5IgEgAhIjUiggAhImUiM
gASIA0j+gBtI9ogBSISA/4DUSJqAB0iDSOxI+kj5SLyAEEjDSPVI0kiCgAVIjkjiSNpI9kjt
SImAD0jSSPwISLuABUieSPRI60jcSPlIzYAPSLpI6ghI4YAFSLFI/EjmSLpI70jtSKGADkjG
CEjwSPlIooAESMAISN4ASOBI80jSgA5I0whIzEj7SOGABEjUSP1IxABIqUj4SOdIuIANSN4I
SMBI40j0SLqAA0jcSO1IsIABSLwISOBImoAMSOJI70idSM1I9UjcSIaAAkjgSPJIpIABSIlI
ywhI00iCgAtI4EjtSJxIjEjuSPVIsoABSJ9I+EjxSI6AAkioSNsISL+ACkigSPhI8EiMAEi8
CEjhgAFItEj3SNiABEi+SOhI+Ei9gAlImkjuSOVIgABIj0jcSP1IuwBIyghI0YAFSNBI+0jt
SL2ACEiXSOtI4YACSMRI6EjlSIZI2whIxIAGSMpI/kjqSLKAB0inSPpI7kiGgAFIkUjsSOlI
ukjeSPdIsIAGSIJI5QhI7UijgAZInUjtSN6AA0jDCEjmSPFI9UikgAdIokjmSPRIqYAGSKBI
8EjigANIh0jlSPZI/EjqSH+ACEiJSJuACEiWSImABEitSPMISNyAHEi6SOBIv4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4DtAP//AP//AP//Af/+gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+AlkKAQs5CwYAc
Qs9C9kLoQoCAGkKIQuxC80K7gAVChoAVQtBC2EKFgAVC5EKMgB1C50KTgB1C+EKygB1C+0LJ
gB1C70LSgB1C7ELQgB1C8ULqQoaAHELnQvZCpID/gP+Ak0K2AkL9QpKAGkKyggOAGoIEgARC
hYATQoKCBIAEAkLngBOCA0KOgASCAUKRgBJCsYIBQsmABYIBQqyAHIIBQsuAHIIBQvmAHIIC
gByCAoAcggJCgYAbggJCs4D/gP+Ac0KIgB2CAkLwgBqCBEKqgBhCsoIEQs+AA0LhQomAEkLe
ggRCmIADggFCj4ARQsGCA0LrgASCAULvgBKCA4AFggKAE0KjQquABoICgByCAoAcggJCnoAb
ggJCwoAbggJC3YAbggOAGwAAAAAAAAAAAAAAAYD/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP9Cz0LzQraAHELH
QupCuoAcQr9C+ELQgBxCqkL3QuSAFEKiQp6ABUKJQuhC60KQgBJClELtQulCiIAFQtpC4kKc
gBJCl0LlQtaABkLbQvRCrIASQp5C7ULegAZCzkL8QsiAEkKyQvhC3oAGQrRC9kLXgBJCvUL6
QtWABkKiQuhC3YASQsFC80LEgAZClkLoQt5CiIARQrtC7EK+gAZCg0LnQu9CmoARQtBC+EK+
gAdC3UL6QrWAEULcQvpCtoAHQsxC/ELKgBFC00L2QriAB0K2QvhC2IARQsJC6EKwgAdCn0Lt
QuGAEULNQvVCvIAHQpNC5ELjQo6AEELOQvxCyIAHQoFC40LpQpyAEELGQvlCyoAIQttC9UKv
gBBCv0L2QsuACELOQvtCxoAQQrdC8kLMgAhCvUL7QtmAEEK0QvNC0YAIQpRC0EKvgBBCsUL0
QtaAHEKlQvJC6UKEgBxCsEKngGFItkimgBxIpkj1SORIgoAbSMdI90j5SMSAA0iJSKhIvUjF
SLZIn0iLgBBIy0jkSPNI6UiNgAJI3kj1SPtI/Ej3SN5I6kjgSM9IsEiVgAtIhkjdSPNI2Ej7
SLyAAkjXSOdI10jQSNhI1kjtSPhI+0j3SOlI10ifgAlIp0jtSOdIrEjtSPCCAkLZgBuCAkLz
gBuCA4ATQrZCsoAFggOAEoICQvqABIIDQpOAEEKZggNChYADggNCs4AQQqaCA4AEggNCx4AQ
Qq2CA4AEggNC94AQQsuCA4AEQvaCA4AQQuKCA4AEQsCCA4AQQvCCAkL3gARCoYIDQpGAD0L1
ggJC8YAFggNCrIAPggNC5oAFggNC0YAPggNC1IAFggNC+oAPggNC2oAFQtWCA4APggNC14AF
QryCA4APggNC5IAFQp6CA0KVgA6CA0L2gAaCA0K0gA5C9YICQv6ABoIDQs+ADkLqggOABoID
QvSADkLdggOABkLhggOADkLXggOABkKzggJC74AOQs+CA4AHQscCQuWAD0LCggOAG4IDgBxC
zULEgCBIi0jXSMaAHIgCSPaAGki3iANIq4ACSJBIu0jhSPFI1Ui9SIqAD0j4iASAAUjYiAhI
3EitgAuIBYABiAxIy4AISIyIBYABiA6AB0jIiAWCA4AbggOAG4IDQpCAEUK7ggFCr4AEggNC
wYAQQq2CA0KYgAOCA0LygBBC+YIDQuKAA4IEgBCCBELOgAOCBIAQggRCwoADggRCl4APggRC
roADggRCq4APggRCk4ADggRCyoAPggSABIIEQu+AD4IEgARC14IEgA5CiIIEgARCqYIEgA5C
p4IEgAWCBIAOQpSCBIAFggRCn4ANQoSCBIAFggRCy4ANQoWCBIAFQv6CA0LzgA6CBIAFQteC
BIAOggSABUKsggSADoIEQn+ABYIEgA6CBEKIgAWCBEKbgA2CBEKTgAWCBIAOggRCvIAFQo2C
AkLFgA6CBELZgAdCgoAQQsKCA0KZgBpC14IBQr2AH0joiAFIuIAaSNiIA0iKgBmIBYABSIVI
74gESOhItUiBgA2IBYABiAtI0oAJSKSIBQBIxIgNSKWAB0jqiAUASL6IDkjEgAaIBgAAAAAA
AAAAAAAAAYD/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+AA0iDAEjUyOwBSJJIr0jGSN1I7Ej8SOtIqYAISL9I
9UjTAEjISPeABEjUSOdI7kikgANIm0jSSPJI24AISNNI90i5AEiYSNuAA0jTSOZI70ihgAVI
nMjpAUiNgAZIkEjpSPBImYABSN6AAkjRSOpI70ijgAZIgEjbSOdIpYAGSK1I9kjggAJIuIAB
SM5I7kjvSKmACEjVSPJIwIAGSOBI+UixgAJIlQBIy0jxSO5IroAJSL5I9EjXgAVIsUj2SNtI
iIAESMlI7EiygApIukj4SNSABUjYSOtIxIAESJ5I9EjqSIWACUiQSNJI+0jDgARIo0jhSOpI
n4AESMpI8ki5gAlImUjNSPpI0EicgARIvkj2SNaABUjESOtIv4AGSIJInkiuSNdI+UjaSKeA
BEiESOdI9UikgAVIqEj2SOSAAkiSSJ9Iu0jYSOZI7UjlSPdI2UidgAVIvkj6SNSABkiRSO1I
60iySMJI4EjqSOBI+Uj4SO5I3kjWSMxIhIAGSKBI2Ei0gAdI30j2SPhI90j5SOVI20jVSLdI
nkiJgBRIwkjqSN1IykiwSIiAGkiGgP+A/4A+SMOIDUjUgAZI/ogFgAJIuIgFSMZI84gFgAaI
A0jdiAGAAUi1iAWAA0jNiANIj4AESKWIA0igiAEASLGIBYAESICIA0jCgARI9ogDAEjbCEit
iAWABogDSPKAA0iHiANI6gBIs4gGgAdI74gDgANIzIgDSJ6AAYgFgAhI3YgDgAOIBIACSNeI
A4AISMKIA0j8gAJIwogDSLGAAkiFiAOABkitSNiIBEjDgAKIBIAEiAOAAUiXSMFI34gHSNOA
AkiniANIy4AEiANI9ogKSOiAA0jliANIgIAEiA5I3IAESMSIAkjwgAWIDUi4gAZI3ghI9YAG
iAhI10i9SJGAE0iSiANIyEiegBpIf4D/gP+AHogPgAVIgIgGgAKIDkiygARIxIgGgAGIBki9
gAFIr4gESO2ABIgHAIgGSLuAA0jciASAA0iDiARIuYgISMCABEigiASAA0jkiAQAiAdIx4AG
iARIooACiAUASLaIBUjOgAZIh4gESJWAAUi2iARIlIABiARI2YAGSJmIBYACiAWAAkjhiANI
pYADSJ1I14gHgAFIpogESLGAA4gDSJ9ItEj3iApInYABiAWABIgQSLWAAogESNyABIgPSKGA
A4gEgAWIDoAFSKaIAkjQgAWICkjwSLtIgIAISJyAB0jxiAVI00iVgBdIq0jbSK6A/4D/gBsA
AP8AAP8AAP8AAf6A/4D/gFdCiIAdggJC8YAaggRCq4AYQrKCBELQgANC4kKKgBJC34IEQpmA
A4IBQpCAEULCggNC7IAEggFC8IASggOABYICgBNCo0KrgAaCAoAcggKAHIICQp+AG4ICQsOA
G4ICQt6AG4IDgP+A/4CSQrmCAUKVgBpCtIIDgBqCBIAEQoeAE0KFggSABAJC6oATggNCkIAE
ggFClIASQrOCAULMgAWCAUKugByCAULOgByCAUL8gByCAoAcggKAHIICQoSAG4ICQrWA/4D/
gLJChELTQsaAHELUQvtC7UKEgBpCjELxQvhCv4AFQoqAFULUQt1CiYAFQulCkYAdQuxCmIAd
Qv1CtoAdAkLOgB1C9ELXgB1C8ULUgB1C9kLvQouAHELsQvtCqYD/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
HAAAAAAAAAAAAAAAAYIDgBuCA4AbggNCkYARQryCAUKwgASCA0LCgBBCroIDQpmAA4IDQvOA
EEL6ggNC44ADggSAEIIEQs+AA4IEQoOAD4IEQsSAA4IEQvWAD4IEQq+AA4IFgA+CBEKUgAOC
BELLgA+CBIAEggRC8IAPggSABELYggSADkKJggSABEKpggSADkKoggSABYIEgA5ClYIEgAWC
BEKggA1ChYIEgAWCBELMgA1ChoIEgAWCBEL0gA6CBIAFQtiCBIAOggSABUKtggSADoIEQoCA
BYIEgA6CBEKJgAWCBEKcgA2CBEKUgAWCBIAOggRCvYAFQo6CAkLGgA6CBELagAdCg4AQQsSC
A0KagBpC2IIBQr6AH0jqiAFIuYAaSNmIA0iLgBmIBYABSIZI8IgESOlItkiCgA2IBYABiAtI
1IAJSKWIBQBIxYgNSKaAB0jriAUASL+IDkjFgAaIBoICQtyAG4ICQveAG4IDgBNCuUK1gAWC
A4ASggJC/YAEggNCloAQQpyCA0KIgAOCA0K2gBBCqYIDgASCBEKDgA9CsIIDgASCBEL1gA9C
zoIDgASCBYAPQuWCA4AEggRCv4APQvSCAkL7gASCBEKTgA9C+YICQvSABYIDQq+AD4IDQuqA
BYIDQtSAD4IDQteABYIDQv2AD4IDQt6ABULYggOAD4IDQtuABUK/ggOAD4IDQueABUKhggNC
l4AOggNC+YAGggNCt4AOQvmCA4AGggNC0oAOQu2CA4AGggNC94AOQuCCA4AGQuSCA4AOQtqC
A4AGQraCAkLygA5C0oIDgAdCygJC6IAPQsWCA0KAgBqCA4AcQtBCx4AgSI5I2kjKgBtIf4gC
SPqAGki6iANIroACSJNIvkjlSPVI2UjASI2AD0j8iASAAUjbiAhI4EiwgAuIBYABiAxIzoAI
SI+IBYABiA6AB0jLiAVC1EL4QruAHELMQu9Cv4AcQsRC/kLVgBxCr0L9QumAFEKnQqOABUKO
Qu1C8EKVgBJCmULzQu5CjYAEQoJC30LnQqGAEkKcQutC3IAFggNC04ARQqNC80LjgAWCBEKX
gBBCt0L+QuSABYIEQquAEELDAkLbgAWCBIARQsZC+ELJgAVCp0KaQu5C40KNgBFCwELyQsOA
BkKHQuxC9UKegBFC1UL9QsOAB0LiAkK6gBFC4gJCu4AHQtECQs6AEULZQvxCvYAHQrtC/ULd
gBFCx0LuQrWAB0KjQvJC5kJ/gBBC0kL6QsGAB0KXQulC6EKSgBBC0wJCzYAHQoVC6ELvQqCA
EELLQv5Cz4AIQuBC+0K0gBBCxEL7QtGACELTAkLLgBBCvEL3QtGACELCAkLegBBCuUL5QtaA
CEKYQtRCtIAQQrZC+ULbgBxCqkL3Qu5CiYAcQrVCrIBhSLtIq4AcSKxI+0jqSIeAG0jMSP0I
SMmAA0iOSK5Iw0jLSLtIpEiRgBBI0EjqSPlI70iSgAJI5Ej8iAFI/UjkSPFI5kjVSLVImoAL
SItI40j5SN4ISMGAAkjdSO1I3UjWSN1I3EjzSP4ISP1I70jcSKSACUisSPNI7UixSPNI9oC/
QonChQGAHELtwuQBQt5CjIAaQvZC6ML0AUKggBpCn0KOQqxCqoD/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4DbAAAA
AAAAAAAAAAABgAGID4AFSIGIBoACiA5ItIAESMWIBoABiAZIvoABSLCIBEjugASIBwCIBki8
gANI3YgEgANIhIgESLqICEjBgARIoYgEgANI5YgEAIgHSMiABogESKOAAogFAEi3iAVIz4AG
SIiIBEiWgAFIt4gESJWAAYgESNqABkiaiAVIgIABiAWAAkjiiANIpoADSJ9I2IgHgAFIp4gE
SLKAA4gDSKBItUj4iApInoABiAWABIgQSLeAAogESN2ABIgPSKKAA4gEgAWIDoAFSKeIAkjR
gAWICkjxSLxIgYAISJ2AB0jyiAVI1EiWgBdIrEjdSK+A/4D/gB1Ix4gNSNeABogGgAJIvIgF
SMpI94gFgAaIA0jgiAGAAUi5iAWAA0jQiANIkoAESKiIA0ijiAEASLWIBYAESIOIA0jFgARI
+ogDAEjfCEiwiAWABogDSPWAA0iKiANI7gBItogGgAdI84gDgANIz4gDSKKAAYgFgAhI4IgD
gAOIBIACSNqIA0iAgAdIxYgEgAJIxogDSLSAAkiIiAOABkiwSNyIBEjHgAKIBIAEiAOAAUib
SMVI44gHSNeAAkiqiANIzoAEiANI+ogKSOuAA0joiANIg4AEiA5I4IAESMeIAkjzgAWIDUi7
gAZI4ghI+IAGiAhI2kjASJSAE0iWiANIy0ihgBpIg4D/gP+AIEiIAEjayPIBSJhItUjMSONI
8ghI8UivgAhIxEj7SNkASM1I/YAESNpI7Uj0SKqAA0igSNdI+EjhgAhI2Uj9SL8ASJ1I4YAD
SNhI7Ej1SKeABUihyO8BSJKABkiVSO9I9kiegAFI5IACSNZI8Ej1SKiABkiFSOFI7kirgAZI
s0j8SOaAAki+gAFI1Ej0SPVIroAISNtI+EjGgAZI5ghItoACSJoASNFI90j0SLOACUjDSPpI
3YAFSLZI/EjgSI2ABEjOSPJIuIAKSL9I/kjagAVI3kjxSMmABEikSPpI8EiKgAlIlUjXCEjJ
gARIqEjnSPBIpIAESNBI+Ei/gAlInkjTCEjWSKGABEjDSPxI24AFSMpI8kjEgAZIh0ijSLNI
3QhI30itgARIiUjtSPtIqYAFSK5I/EjqgAJIl0ilSMFI3UjsSPNI60j9SN9IooAFSMQISNqA
BkiWSPNI8Ui4SMhI5kjwSOYISP5I9EjkSNxI0kiKgAZIpUjeSLmAB0jlSPxI/kj9CEjrSOFI
20i8SKRIjoAUSMdI8EjjSNBItkiNSIGAGUiLgP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+APAD//wD/
/wD//wH//4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+AZ0jJSNhIi4AbSIxI7Uj0SKyAG0iSSOVI
30jwSLWAGkibSOtI4EjuSOtIr4ASSJqABUilSPBI3EjOSPFI5kiogP+A/4D/gFhIoogBSM6A
G4gDSJqAGUiJiARIgYASSKyABEiciAWAEgiABEiqiAVI+4ARCEjegANIuIgGSNuA/4D/gP+A
OEiYSKaAHIgDSIOAGUi8iANI+oATSJ6ABEjmiARI3YASCIAESPuIBUjNgBEISL6AA4gHSLyA
EIgBgAOICEiDgA8AAAAAAAAAAAAAAAGA/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/SNyABUixSPNI1QBI00j0
SOBIhoAQSOJIl4AESLxI9UjMAEiISOZI7EjPgBBI8kimgARIz0jtSMCAAUisSO5I80i2gA9I
+kjagARI2UjuSKyAAkjFSOtI7UingA5I6kjzSJ2AAkiUSOhI60iRgANI00j4SN9In4ANSMpI
+0jKgAJIvEj7SNiABEiNSNFI/EjjSJuADEinSPJI6kiGgAFI3Ej3SLCABUibSNtI8kjpSKCA
DEjPSO9IvwBIpkjpSNtIl4AGSI1I20jxSOdIqIALSL9I8EjOAEi8SPFI1YAISIZI2Uj1SLaA
C0iFSOpI80i+SOdI9kilgAlIhUikgA1IuUj4SOVI8EjdgBtI3EjwSORI0YAbSIpI3kj8SMyA
HEifSM5IoYD/gP+AWIgBgANIz4gHSLKAD4gBSKqAAkjliAhIiYAOiAFI4oACiANI+kjtiASA
DogCgAKIA0jKAIgESO+ADYgCSMAASLWIA0iVAEibiARI7IAMiAMASN+IA4ACSLqIBEj4gAuI
A0iTiANI4YADSM2IBEj7gAqIA0jxiANIsIAESNWIBEjKgAlI8IgHgAZIz4gDSNiACUiTiAZI
woAHSMyIAkiKgAqIBkiDgAhIk0iygAxIlogFgBlI1IgEgBpI2YgCSNKAG0jRCEjTgP+A/4A4
iAFIqoACiAmAD4gCgAKICUjmgA6IAoABSJmICki3gA2IAkjKAEjViARIzIgFSKOADIgDAIgE
SPMASPuIBUiogAuIA0ihiARIpIABiAZIr4AKiANI8YgEgAJIgogGSL2ACYgJgANIm4gGgAmI
CEihgARIiIgFgAlI8ogHgAeIA0jngAlIoIgGSOCACEjyCEjUgAtI9YgFSLCAGIgFgBlIhIgE
gBpIoogCSKeA/4D/gDcAAP8AAP8AAP8AAf+A/4D/gP+AJ0iaSKiAHIgDSISAGUi9iANI+4AT
SJ+ABEjniARI3oASCIAESP2IBUjOgBEISL+AA4gHSL2AEIgBgAOICEiEgP+A/4D/gFZIpYgB
SNGAG4gDSJ2AGUiMiARIhIASSLCABEifiAWAEgiABEitiAaAEQhI4YADSLuIBkjegP+A/4D/
gHhIz0jeSJCAG0iRSPNI+kixgBtIl0jrSOVI9ki6gBpIoUjxSOVI80jxSLSAEkifgAVIqkj2
SOJI1Ej3SOxIrYD/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/
gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+AEQAAAAAAAAAAAAAAAYgBSKuAAogJgA+IAoAC
iAlI54AOiAKAAUiaiApIuIANiAJIzABI1ogESM2IBUikgAyIAwCIBEj1AEj8iAVIqYALiANI
oogESKWAAYgGSLCACogDSPKIBIACSIOIBki+gAmICYADSJyIBoAJiAhIooAESImIBYAJSPOI
B4AHiANI6YAJSKGIBkjhgAhI8whI1YALSPaIBUiygBiIBYAZSIWIBIAaSKOIAkipgP+A/4A3
iAGAA0jSiAdItoAPiAFIrYACSOiICEiMgA6IAUjlgAKIA0j+SPCIBIAOiAKAAogDSM0AiARI
84ANiAJIwwBIuIgDSJgASJ6IBEjwgAyIAwBI4ogDgAJIvogESPuAC4gDSJaIA0jlgANI0IgF
gAqIA0j1iANIs4AESNiIBEjNgAlI9IgHgAZI0ogDSNuACUiXiAZIxYAHSM+IAkiNgAqIBkiG
gAhIlki1gAxImYgFgBlI14gEgBpI3YgCSNWAG0jUCEjXgP+A/4A4SOGABUi2SPlI2gBI2Ej6
SOVIi4AQSOhInYAESMJI+0jSAEiNSOtI8kjVgBBI90irgARI1UjzSMWAAUixSPRI+Ui8gA8I
SN+AA0iASN5I9EiygAJIy0jxSPNIrIAOSPBI+UiigAJImUjuSPFIloADSNlI/kjlSKSADUjP
CEjQgAJIwQhI3oAESJJI1whI6UihgAxIrUj4SPBIi4ABSOJI/Ui2gAVIoEjhSPhI70ilgAtI
gUjVSPVIxQBIq0juSOFInIAGSJJI4Uj2SO1IroALSMVI9kjTSIFIwUj3SNqACEiMSN5I+ki7
gAtIikjvSPlIw0jsSPxIqoAJSIpIqYANSL5I/kjrSPZI44AbSOFI9kjpSNeAG0iPSOQISNKA
HEikSNNIpoD/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A
/4D/gP+A/4D/gP+A/4D/gP+A/4D/gP+A/4D/gFg=]]"""
MATERIALS: list[Material] = [
	"Air",
	"Water",
	"Grass",
	"Slate",
	"Concrete",
	"Brick",
	"Sand",
	"WoodPlanks",
	"Rock",
	"Glacier",
	"Snow",
	"Sandstone",
	"Mud",
	"Basalt",
	"Ground",
	"CrackedLava",
	"Asphalt",
	"Cobblestone",
	"Ice",
	"LeafyGrass",
	"Salt",
	"Limestone",
	"Pavement",	
]

TerrainGrid = list[list[list[Material]]]
GRID_SIZE = 2048

def read_terrain_from_rbxmx(file_path: str):
	# tree = ET.parse(file_path)
	# root = tree.getroot()
	# Find the SmoothGrid property
	#     for child in root.iter('SmoothGrid'):
	#         terrain_data = child.text
	#         break
	#     else:
		#    raise Exception('SmoothGrid property not found')
	terrain_data = TEST_STR
	terrain_grid = [[[0]*GRID_SIZE for _ in range(GRID_SIZE)] for _ in range(GRID_SIZE)]
	for z in range(GRID_SIZE):
		for y in range(GRID_SIZE):
			for x in range(GRID_SIZE):
				byte = terrain_data[z*GRID_SIZE*GRID_SIZE + y*GRID_SIZE + x]
				terrain_grid[x][y][z] = MATERIALS[struct.unpack('B', byte)[0]]
	return terrain_grid

with open("out.json", "w") as file:
	data = read_terrain_from_rbxmx("test.rbxmx")
	data_str = json.dumps(data, indent=5)
	file.write(data_str)

def write_terrain_to_rbxmx(terrain_grid: TerrainGrid, file_path: str):
    terrain_data = b''
    for z in range(GRID_SIZE):
        for y in range(GRID_SIZE):
            for x in range(GRID_SIZE):
                byte = struct.pack('B', MATERIALS.index(terrain_grid[x][y][z]))
                terrain_data += byte

    tree = ET.parse(file_path)
    root = tree.getroot()
    # Find the SmoothGrid property and replace the text
    for child in root.iter('SmoothGrid'):
        child.text = terrain_data
        break
    else:
        raise Exception('SmoothGrid property not found')

    tree.write(file_path)

